package com.webtoapp.template;

import android.app.Activity;
import android.content.Intent;
import android.os.Bundle;
import android.util.Log;

import androidx.core.content.ContextCompat;
import androidx.credentials.Credential;
import androidx.credentials.CredentialManager;
import androidx.credentials.CredentialManagerCallback;
import androidx.credentials.CustomCredential;
import androidx.credentials.GetCredentialRequest;
import androidx.credentials.GetCredentialResponse;
import androidx.credentials.exceptions.GetCredentialCancellationException;
import androidx.credentials.exceptions.GetCredentialException;

import com.google.android.gms.auth.api.signin.GoogleSignIn;
import com.google.android.gms.auth.api.signin.GoogleSignInAccount;
import com.google.android.gms.auth.api.signin.GoogleSignInClient;
import com.google.android.gms.auth.api.signin.GoogleSignInOptions;
import com.google.android.gms.common.api.ApiException;
import com.google.android.gms.tasks.Task;
import com.google.android.libraries.identity.googleid.GetSignInWithGoogleOption;
import com.google.android.libraries.identity.googleid.GoogleIdTokenCredential;

/**
 * Invisible helper activity that runs the NATIVE Google sign-in flow — the
 * device's own account chooser instead of the manual email/password page a
 * WebView gets. Started by JavaScriptBridge.googleSignIn(); the resulting
 * Google ID TOKEN is handed back through {@link Callback} so the web page can
 * finish login with Firebase signInWithCredential().
 *
 * PRIMARY flow: Credential Manager ("Sign in with Google") — Google's current
 * API. The legacy GoogleSignIn SDK is deprecated and its re-grant path fails
 * with DEVELOPER_ERROR(10) on some devices after the first successful login
 * ("works once after install", Ali t310); Credential Manager does not use that
 * path. The legacy flow is kept as an automatic FALLBACK for devices whose
 * Play Services is too old for Credential Manager.
 *
 * The web client id comes from the Firebase config (string resource
 * "default_web_client_id", generated by the google-services plugin). Looked up
 * BY NAME at runtime so apps built without Firebase simply report
 * "google_signin_not_available" instead of failing to compile.
 */
public class GoogleSignInActivity extends Activity {

    private static final String TAG = "GoogleSignIn";
    private static final int RC_SIGN_IN = 9301;

    /** One-shot result receiver set by the bridge just before launch. */
    public interface Callback {
        void onResult(String idToken, String error);
    }

    private static Callback pendingCallback;

    public static void setCallback(Callback cb) {
        pendingCallback = cb;
    }

    private static void deliver(String idToken, String error) {
        Callback cb = pendingCallback;
        pendingCallback = null;
        if (cb != null) cb.onResult(idToken, error);
    }

    private String webClientId;

    @Override
    protected void onNewIntent(Intent intent) {
        super.onNewIntent(intent);
        setIntent(intent);
    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        // Web client id: generated by the google-services plugin when Firebase is
        // configured. Resolved by name so a Firebase-less build still compiles.
        int resId = getResources().getIdentifier("default_web_client_id", "string", getPackageName());
        if (resId == 0) {
            Log.w(TAG, "default_web_client_id missing — Firebase not configured for this app");
            deliver("", "google_signin_not_available");
            finish();
            return;
        }
        webClientId = getString(resId);

        try {
            credentialManagerFlow();
        } catch (Throwable t) {
            // Credential Manager classes unavailable/broken on this device — legacy.
            Log.w(TAG, "Credential Manager unavailable, using legacy flow", t);
            legacyFlow();
        }
    }

    /** Modern flow: Credential Manager "Sign in with Google" dialog. */
    private void credentialManagerFlow() {
        CredentialManager cm = CredentialManager.create(this);
        GetSignInWithGoogleOption option = new GetSignInWithGoogleOption.Builder(webClientId).build();
        GetCredentialRequest request = new GetCredentialRequest.Builder()
                .addCredentialOption(option)
                .build();
        cm.getCredentialAsync(this, request, null, ContextCompat.getMainExecutor(this),
                new CredentialManagerCallback<GetCredentialResponse, GetCredentialException>() {
                    @Override
                    public void onResult(GetCredentialResponse response) {
                        try {
                            Credential cred = response.getCredential();
                            if (cred instanceof CustomCredential
                                    && GoogleIdTokenCredential.TYPE_GOOGLE_ID_TOKEN_CREDENTIAL.equals(cred.getType())) {
                                GoogleIdTokenCredential gid =
                                        GoogleIdTokenCredential.createFrom(((CustomCredential) cred).getData());
                                String idToken = gid.getIdToken();
                                if (idToken != null && !idToken.isEmpty()) {
                                    deliver(idToken, "");
                                } else {
                                    deliver("", "no_id_token");
                                }
                            } else {
                                deliver("", "unexpected_credential_type");
                            }
                        } catch (Exception e) {
                            Log.e(TAG, "Credential parse failed", e);
                            deliver("", "credential_parse_failed");
                        }
                        finish();
                    }

                    @Override
                    public void onError(GetCredentialException e) {
                        if (e instanceof GetCredentialCancellationException) {
                            Log.w(TAG, "Credential Manager: user cancelled");
                            deliver("", "cancelled");
                            finish();
                            return;
                        }
                        // Any other failure (no provider, old GMS, no credential):
                        // fall back to the legacy account-chooser flow rather than
                        // failing the login outright.
                        Log.w(TAG, "Credential Manager failed (" + e.getClass().getSimpleName()
                                + ") — falling back to legacy sign-in", e);
                        legacyFlow();
                    }
                });
    }

    /** Legacy fallback: deprecated GoogleSignIn SDK account-chooser intent. */
    private void legacyFlow() {
        try {
            GoogleSignInOptions gso = new GoogleSignInOptions.Builder(GoogleSignInOptions.DEFAULT_SIGN_IN)
                    .requestIdToken(webClientId)
                    .requestEmail()
                    .build();
            GoogleSignInClient client = GoogleSignIn.getClient(this, gso);
            // revokeAccess (implies signOut) so the chooser always shows and the
            // failure-prone re-grant path is avoided where possible.
            client.revokeAccess().addOnCompleteListener(t ->
                    startActivityForResult(client.getSignInIntent(), RC_SIGN_IN));
        } catch (Exception e) {
            Log.e(TAG, "Google sign-in init failed", e);
            deliver("", "google_signin_init_failed");
            finish();
        }
    }

    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        if (requestCode != RC_SIGN_IN) return;
        Task<GoogleSignInAccount> task = GoogleSignIn.getSignedInAccountFromIntent(data);
        try {
            GoogleSignInAccount account = task.getResult(ApiException.class);
            String idToken = account != null ? account.getIdToken() : null;
            if (idToken != null && !idToken.isEmpty()) {
                deliver(idToken, "");
            } else {
                deliver("", "no_id_token");
            }
        } catch (ApiException e) {
            // 12501 = user cancelled the chooser — not an error worth alarming over.
            String err = (e.getStatusCode() == 12501) ? "cancelled" : ("signin_failed_" + e.getStatusCode());
            Log.w(TAG, "Google sign-in result: " + err);
            deliver("", err);
        }
        finish();
    }
}
