package com.webtoapp.template;

import android.app.Activity;
import android.content.Intent;
import android.os.Bundle;
import android.util.Log;

import com.google.android.gms.auth.api.signin.GoogleSignIn;
import com.google.android.gms.auth.api.signin.GoogleSignInAccount;
import com.google.android.gms.auth.api.signin.GoogleSignInClient;
import com.google.android.gms.auth.api.signin.GoogleSignInOptions;
import com.google.android.gms.common.api.ApiException;
import com.google.android.gms.tasks.Task;

/**
 * Invisible helper activity that runs the NATIVE Google sign-in flow — the
 * device's own account chooser ("pick an account" sheet) instead of the manual
 * email/password page a WebView gets. Started by JavaScriptBridge.googleSignIn();
 * the resulting Google ID TOKEN is handed back through {@link Callback} so the
 * web page can finish login with Firebase signInWithCredential().
 *
 * The web client id comes from the Firebase config (string resource
 * "default_web_client_id", generated by the google-services plugin). Looked up
 * BY NAME at runtime so apps built without Firebase simply report
 * "google_signin_not_available" instead of failing to compile.
 */
public class GoogleSignInActivity extends Activity {

    private static final String TAG = "GoogleSignIn";
    private static final int RC_SIGN_IN = 9301;

    /** One-shot result receiver set by the bridge just before launch. */
    public interface Callback {
        void onResult(String idToken, String error);
    }

    private static Callback pendingCallback;

    public static void setCallback(Callback cb) {
        pendingCallback = cb;
    }

    private static void deliver(String idToken, String error) {
        Callback cb = pendingCallback;
        pendingCallback = null;
        if (cb != null) cb.onResult(idToken, error);
    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        // Web client id: generated by the google-services plugin when Firebase is
        // configured. Resolved by name so a Firebase-less build still compiles.
        int resId = getResources().getIdentifier("default_web_client_id", "string", getPackageName());
        if (resId == 0) {
            Log.w(TAG, "default_web_client_id missing — Firebase not configured for this app");
            deliver("", "google_signin_not_available");
            finish();
            return;
        }
        String webClientId = getString(resId);

        try {
            GoogleSignInOptions gso = new GoogleSignInOptions.Builder(GoogleSignInOptions.DEFAULT_SIGN_IN)
                    .requestIdToken(webClientId)
                    .requestEmail()
                    .build();
            GoogleSignInClient client = GoogleSignIn.getClient(this, gso);
            // revokeAccess (implies signOut) rather than signOut alone: with a
            // prior grant left from the last session, Play Services routes the
            // next sign-in through the RE-GRANT path, which fails with
            // DEVELOPER_ERROR(10) on some console setups even though the
            // fresh-consent path works ("works once after install, error 10
            // afterwards" — Ali, t310). Revoking the old grant forces every
            // sign-in down the fresh-consent path that provably works, and the
            // account CHOOSER still always shows (which we want anyway).
            client.revokeAccess().addOnCompleteListener(t ->
                    startActivityForResult(client.getSignInIntent(), RC_SIGN_IN));
        } catch (Exception e) {
            Log.e(TAG, "Google sign-in init failed", e);
            deliver("", "google_signin_init_failed");
            finish();
        }
    }

    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        if (requestCode != RC_SIGN_IN) return;
        Task<GoogleSignInAccount> task = GoogleSignIn.getSignedInAccountFromIntent(data);
        try {
            GoogleSignInAccount account = task.getResult(ApiException.class);
            String idToken = account != null ? account.getIdToken() : null;
            if (idToken != null && !idToken.isEmpty()) {
                deliver(idToken, "");
            } else {
                deliver("", "no_id_token");
            }
        } catch (ApiException e) {
            // 12501 = user cancelled the chooser — not an error worth alarming over.
            String err = (e.getStatusCode() == 12501) ? "cancelled" : ("signin_failed_" + e.getStatusCode());
            Log.w(TAG, "Google sign-in result: " + err);
            deliver("", err);
        }
        finish();
    }
}
