import psycopg2
conn = psycopg2.connect('postgresql://webtoapp:webtoapp@127.0.0.1:5434/webtoapp')
cur = conn.cursor()
cur.execute("SELECT id, pipeline_id, variables, status, apk_url, aab_url, error_message, log, progress, started_at, completed_at FROM builds WHERE order_id = '96d9d481-f73e-4e0d-b0a8-dcb7f7f8452c' ORDER BY created_at DESC LIMIT 3")
rows = cur.fetchall()
print(f'Rows: {len(rows)}')
for row in rows:
    print('---')
    print('ID:', row[0])
    print('pipeline_id:', row[1])
    print('vars keys:', list((row[2] or {}).keys()) if row[2] else None)
    print('status:', row[3])
    print('apk_url:', row[4])
    print('aab_url:', row[5])
    print('error_message:', row[6])
    print('log len:', len(row[7]) if row[7] else 0)
    print('progress:', row[8])
    print('started:', row[9])
    print('completed:', row[10])
conn.close()
