name: WebToApp
options:
  deploymentTarget:
    iOS: "14.0"
  createIntermediateGroups: true
targets:
  App:
    type: application
    platform: iOS
    sources:
      - App
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: __BUNDLE_ID__
        PRODUCT_NAME: App
        INFOPLIST_FILE: App/Info.plist
        MARKETING_VERSION: "1.0.__VERSION_CODE__"
        CURRENT_PROJECT_VERSION: "__VERSION_CODE__"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        TARGETED_DEVICE_FAMILY: "1,2"
        SWIFT_VERSION: "5.0"
        CODE_SIGN_STYLE: Manual
        CODE_SIGN_IDENTITY: ""
        CODE_SIGNING_REQUIRED: "NO"
        CODE_SIGNING_ALLOWED: "NO"
